### ISSUE TITLE
MetaMask breaking change - no more global web3 object

### ISSUE THREAD

**Issue by hudsonburgess** [decentraland/dappeteer#3]
MetaMask just announced a breaking change, effective 2-Nov-2018

https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8

How is that going to affect this project?

**Comment by cazala** [comment]
dApps should still support old versions of MetaMask and/or browsers that inject web3, and since this package uses MetaMask v4.7.4 which injects web3, you can still use it. What we will probably do after MetaMask releases the opt-in feature is update the extension used by this package to the newer one, and add some method to accept the opt-in from the e2e tests, like:

```js
const page = await browser.newPage()
await page.goto('http://my-dapp.com')
const loginButton = await page.$('#login')
await loginButton.click()
  
await metamask.confirmOptIn()
```

**Comment by cazala** [comment]
`dappeteer@0.4.0` works with metamask v5+
